version: '3.9'

networks:
  kong-network:
    external: false


services:
  kong-migrations:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - kong-network
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_DATABASE: postgres
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    restart: always
    networks:
      - kong-network
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_DATABASE: postgres
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_PATH: /manager
      KONG_ADMIN_GUI_URL: http://localhost:8002/manager
    ports:
      - "8001:8001"
      - "8000:8000"
    depends_on:
      - kong-migrations
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 10

  kong-database:
    image: postgres:13
    restart: always
    networks:
      - kong-network
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5